### ISSUE TITLE
Dodati rotaciju pogleda

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-062-thrower#1]
Dodati rotaciju pogleda oko x-ose mišem (ili klik-i-povlačenje, ili preko skrola na mišu) - da se iz sadašnjeg pogleda može preći u perspektivni - nalik:

![](http://www.searchamateur.com/pictures/tetris-3d-x-online-game.jpg)

**Comment by radoje-vujasevic** [comment]
Dodato. Rotira se pomoću skrola. Nisam mogao da se setim kako bih sam to uradio, pa sam pogledao primer sa čajnikom i osvetljenjem i bazirao sam rešenje na njemu.
