### ISSUE TITLE
Detekcija kolizije ima probleme

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-062-thrower#3]
U nekim situacijama kolizija strele i sfere ne radi kako bi trebalo (strela prodje kroz sferu)

**Comment by radoje-vujasevic** [comment]
Probelm detektovan. Ispravljeno. Problem: Kada sam pozvao funkciju glutSolidSphere, kao argument sam zadao veličinu prečnika, a ne poluprečnika
