### ISSUE TITLE
Organizacija koda

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG16/RG16-062-thrower#4]
Probajte da bolje organizujete kod - tako da nema razloga da proveravate koji je trenutni nivo unutar tajmera. Razmislite šta bi trebalo da promenite da bi ubuduće bilo lakše da dodajete nove nivoe

**Comment by radoje-vujasevic** [comment]
Urađeno. Dodao sam makro MAX_NIVOA koji samo treba da se promeni u slučaju da želi da se promeni broj nivoa. Mada nivoi nemaju poentu ako ih je preko 4 ili 5.

**Comment by radoje-vujasevic** [comment]
Vektor brzine za x i y su konstantni ako je nivo < MAX_NIVOA/2
Smer kretanja y ose ne postoji ako je nivo < MAX_NIVOA/2
Boje pozadine se menjaju shodno nivoima.
